language: java
jdk:
- oraclejdk7
- openjdk7
before_script:
- wget http://s3.amazonaws.com/Minecraft.Download/versions/${MC_VERSION}/minecraft_server.${MC_VERSION}.jar
script:
- mvn test -Dminecraftjar=minecraft_server.${MC_VERSION}.jar
env:
- MC_VERSION=1.6.4
- MC_VERSION=13w42a
